version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: ./docker-compose/php/Dockerfile
    image: imocaphp
    container_name: imocaphp
    restart: unless-stopped
    tty: true
    working_dir: /app/
    ports:
      - 8000:80
    volumes:
      - ./app/:/app
    networks:
      - imoca_network

  db:
    image: mysql:5.7
    container_name: imoca-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./storage/mysql:/var/lib/mysql
    networks:
      - imoca_network

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    depends_on:
      - db
    networks:
        - imoca_network

networks:
  imoca_network:
    driver: bridge